### ISSUE TITLE
exporter/zipkin: missing endpoints in payload cause a panic

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#230]
Steps to reproduce:

* Download latest collector
* Configure to receive OC agent (--receiver-oc-trace)
* Configure debug-tracer with log level set to debug
* Configure to send to a Zipkin exporter
* Run example/main.go pointed at collector

Expected: Traces are received by Zipkin exporter

Actual: crash seen in OC collector logs

**Comment by odeke-em** [comment]
Thank you @flands for filing this bug!

So running the same setup with cmd/ocagent works, (with a minor edit of 
```diff
diff --git a/cmd/ocagent/config.go b/cmd/ocagent/config.go
index 6a814a5..4acecca 100644
--- a/cmd/ocagent/config.go
+++ b/cmd/ocagent/config.go
@@ -183,7 +183,7 @@ func (c *config) checkLogicalConflicts(blob []byte) error {
 			zExporterHostPort, zReceiverHostPort)
 	}
 	zExpHost, zExpPort, _ := net.SplitHostPort(zExporterHostPort)
-	zReceiverHost, zReceiverPort, _ := net.SplitHostPort(zExporterHostPort)
+	zReceiverHost, zReceiverPort, _ := net.SplitHostPort(zReceiverHostPort)
 	if eqHosts(zExpHost, zReceiverHost) && zExpPort == zReceiverPort {
 		return fmt.Errorf("ZipkinExporter address (%q) aka (%s on port %s)\nis the same as the receiver address (%q) aka (%s on port %s)",
 			zExporterHostPort, zExpHost, zExpPort, zReceiverHostPort, zReceiverHost, zReceiverPort)
@@ -192,7 +192,7 @@ func (c *config) checkLogicalConflicts(blob []byte) error {
 	// Otherwise, now let's resolve the IPs and ensure that they aren't the same
 	zExpIPAddr, _ := net.ResolveIPAddr("ip", zExpHost)
 	zReceiverIPAddr, _ := net.ResolveIPAddr("ip", zReceiverHost)
-	if zExpIPAddr != nil && zReceiverIPAddr != nil && reflect.DeepEqual(zExpIPAddr, zReceiverIPAddr) {
+	if zExpIPAddr != nil && zReceiverIPAddr != nil && reflect.DeepEqual(zExpIPAddr, zReceiverIPAddr) && zExpPort == zReceiverPort {
 		return fmt.Errorf("ZipkinExporter address (%q) aka (%+v)\nis the same as the\nreceiver address (%q) aka (%+v)",
 			zExporterHostPort, zExpIPAddr, zReceiverHostPort, zReceiverIPAddr)
 	}
```

So we need to check in the collector how the receiver is creating nodes because:
a) The ocagent-exporter actually creates a Node on startup time
b) The Zipkin receiver receives a non-nil one in the ocagent

**Comment by odeke-em** [comment]
Alright, I've been able to recreate this by sending a POST payload using cURL to cmd/ocagent/zipkinReceiver
```shell
$ curl -i -X POST -H "Content-Type":"application/json" http://localhost:9410/api/v2/spans --data \
'[{
    "traceId": "4d1e00c0db9010db86154a4ba6e91385",
    "parentId": "86154a4ba6e91385", "id": "4d1e00c0db9010db",
    "kind": "CLIENT","name": "get",
     "timestamp": 1472470996199000,"duration": 207000,
     "tags": {"http.path": "/api","clnt/finagle.version": "6.45.0"}
}]'
```
given config
```yaml
receivers:
    zipkin:
        address: "localhost:9410"

exporters:
    zipkin:
        endpoint: "http://localhost:9411/api/v2/spans"
```

which gives
```shell
$ ./bin/ocagent_darwin --config cfg.yaml 
2018/11/26 20:30:36 "zipkin" trace-exporter enabled
2018/11/26 20:30:36 Running OpenCensus Trace receiver as a gRPC service at "127.0.0.1:55678"
2018/11/26 20:30:36 Running zPages at ":55679"
2018/11/26 20:30:36 Running Jaeger receiver with CollectorThriftPort 14267 CollectHTTPPort 14268
2018/11/26 20:30:45 http: panic serving 127.0.0.1:58514: runtime error: invalid memory address or nil pointer dereference
goroutine 87 [running]:
net/http.(*conn).serve.func1(0xc0004401e0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/net/http/server.go:1769 +0xc9
panic(0x1929220, 0x22c9a90)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:513 +0x1b7
github.com/census-instrumentation/opencensus-service/exporter/exporterparser.(*zipkinExporter).zipkinSpan(0xc0002a41e0, 0x0, 0xc0004b83c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/emmanuelodeke/go/src/github.com/census-instrumentation/opencensus-service/exporter/exporterparser/zipkin.go:303 +0xd3
github.com/census-instrumentation/opencensus-service/exporter/exporterparser.(*zipkinExporter).ExportSpans(0xc0002a41e0, 0x1bec6c0, 0xc0004a0ae0, 0x0, 0xc000498180, 0x1, 0x1, 0x1, 0x1)
	/Users/emmanuelodeke/go/src/github.com/census-instrumentation/opencensus-service/exporter/exporterparser/zipkin.go:190 +0xab
github.com/census-instrumentation/opencensus-service/exporter.traceExporters.ReceiveSpans(0xc00036a7f0, 0x1, 0x1, 0x1bec6c0, 0xc0004a0ae0, 0x0, 0xc000498180, 0x1, 0x1, 0xc0004a0d50, ...)
	/Users/emmanuelodeke/go/src/github.com/census-instrumentation/opencensus-service/exporter/trace_exporter.go:60 +0xb0
github.com/census-instrumentation/opencensus-service/receiver/zipkin.(*ZipkinReceiver).ServeHTTP(0xc0002a42d0, 0x1bea3c0, 0xc0004b42a0, 0xc0004a6100)
	/Users/emmanuelodeke/go/src/github.com/census-instrumentation/opencensus-service/receiver/zipkin/trace_receiver.go:252 +0x2cb
net/http.serverHandler.ServeHTTP(0xc0003ac4e0, 0x1bea3c0, 0xc0004b42a0, 0xc0004a6100)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc0004401e0, 0x1bec600, 0xc0004a2500)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/net/http/server.go:1878 +0x847
created by net/http.(*Server).Serve
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/net/http/server.go:2884 +0x2f2
```
