### ISSUE TITLE
build: TestExportProtocolViolations_nodelessFirstMessage is flaky

### ISSUE THREAD

**Issue by tigrannajaryan** [census-instrumentation/opencensus-service#577]
The build https://travis-ci.org/census-instrumentation/opencensus-service/builds/545923792?utm_source=github_status&utm_medium=notification failed with the following:

```
panic: Log in goroutine after TestExportProtocolViolations_nodelessFirstMessage has completed
goroutine 46 [running]:
testing.(*common).logDepth(0xc0000ac800, 0xc000026fe0, 0x18, 0x3)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:614
testing.(*common).Log(0xc0000ac800, 0xc00004e750, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:642 +0x79
github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage.func1(0xc00002c310, 0xc0000ac800, 0x77359400, 0xc0002f5c40)
	/home/travis/gopath/src/github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:194 +0x203
created by github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage
	/home/travis/gopath/src/github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:189 +0x3fb
FAIL	github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics	0.198s
```

**Comment by flands** [comment]
@tigrannajaryan is this still applicable?

**Comment by tigrannajaryan** [comment]
Yes, likely still applicable.
