### ISSUE TITLE
Flaky test: TestExportProtocolViolations_nodelessFirstMessage

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#584]
```terminal
panic: Log in goroutine after TestExportProtocolViolations_nodelessFirstMessage has completed
goroutine 38 [running]:
testing.(*common).logDepth(0xc0000cc500, 0xc0000d07a0, 0x18, 0x3)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:614
testing.(*common).Log(0xc0000cc500, 0xc000053f50, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:642 +0x79
github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage.func1(0xc0002201c0, 0xc0000cc500, 0x77359400, 0xc000250b00)
	/home/travis/gopath/src/github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:194 +0x203
created by github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage
	/home/travis/gopath/src/github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:189 +0x3fb
FAIL	github.com/census-instrumentation/opencensus-service/receiver/opencensusreceiver/ocmetrics	0.203s
```

**Comment by flands** [comment]
@pjanotti is this still applicable?
