### ISSUE TITLE
Integrate Azure Monitor Exporter 

### ISSUE THREAD

**Issue by ChrisCoe** [census-instrumentation/opencensus-service#595]
I have been working on an azure exporter (not fully completed) so that opencensus users can send data to Azure Monitor (https://github.com/census-instrumentation/opencensus-website/issues/644#issuecomment-501052695). The goal here is to replace the current way Azure Monitor users send their telemetry there. I understand at the time opencensus is being merged with another project. Do you have any suggestions on how to proceed?

**Comment by pjanotti** [comment]
Hi @ChrisCoe - we are  OpenTelemetry the idea is to have a clear separation between what is maintained on core vs contrib. The idea being that maintainers of core are responsible for those while the pieces on contrib have others responsible for them.

**Comment by ChrisCoe** [comment]
I am working with @reyang and @lzchen for this project. For now, my goal is to create a prototype I can demo to gauge whether we should fully implement this.

**Comment by pjanotti** [comment]
I see. In order to demo it you should add it to  https://github.com/census-instrumentation/opencensus-service/tree/master/exporter and then to https://github.com/census-instrumentation/opencensus-service/blob/926bd4418c62da3bfb0605997da42013460fa52c/internal/config/config.go#L445. That's it, with those two parts in place you can build and validate it.

**Comment by ChrisCoe** [comment]
I can't seem to run the OC agent from binary. I am on windows and have bzr 2.5.1 and go 1.12.5. I looked at other similar issues, but I still have this problem. Do you have any suggestions? I tried different brazaar versions.

` $ make agent`
`GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/ocagent_windows -ldflags "-X github.com/census-instrumentation/opencensus-service/internal/version.GitHash=baa19a2 " ./cmd/ocagent
go: labix.org/v2/mgo@v0.0.0-20140701140051-000000000287: bzr branch --use-existing-dir https://launchpad.net/mgo/v2 . in C:\Users\t-chcoel\go\pkg\mod\cache\vcs\ca61c737a32b1e09a0919e15375f9c2b6aa09860cc097f1333b3c3d29e040ea8: exit status 4:
        bzr: ERROR: httplib.IncompleteRead: IncompleteRead(34 bytes read)`

      ` Traceback (most recent call last):
          File "bzrlib\commands.pyo", line 920, in exception_to_return_code
          File "bzrlib\commands.pyo", line 1131, in run_bzr
          File "bzrlib\commands.pyo", line 673, in run_argv_aliases
          File "bzrlib\commands.pyo", line 695, in run
          File "bzrlib\cleanup.pyo", line 136, in run_simple
          File "bzrlib\cleanup.pyo", line 166, in _do_with_cleanups
          File "bzrlib\builtins.pyo", line 1438, in run
          File "bzrlib\controldir.pyo", line 779, in open_tree_or_branch
          File "bzrlib\controldir.pyo", line 459, in _get_tree_branch
          File "bzrlib\bzrdir.pyo", line 1082, in open_branch
          File "bzrlib\branch.pyo", line 2375, in open
          File "bzrlib\controldir.pyo", line 687, in open
          File "bzrlib\controldir.pyo", line 716, in open_from_transport
          File "bzrlib\transport\__init__.pyo", line 1718, in do_catching_redirections
          File "bzrlib\controldir.pyo", line 704, in find_format
          File "bzrlib\controldir.pyo", line 1149, in find_format
          File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 235, in probe_transport
          File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 182, in probe_http_transport
          File "socket.pyo", line 348, in read
          File "httplib.pyo", line 522, in read
          File "httplib.pyo", line 565, in _read_chunked
        IncompleteRead: IncompleteRead(34 bytes read)

        bzr 2.5.1 on python 2.6.6 (Windows-post2008Server-6.2.9200)
        arguments: ['bzr', 'branch', '--use-existing-dir',
            'https://launchpad.net/mgo/v2', '.']
        plugins: bzrtools[2.5.0], changelog_merge[2.5.1], colo[0.4.0],
            explorer[1.2.2], fastimport[0.14.0dev], git[0.6.8], launchpad[2.5.1],
            loom[2.3.0dev], netrc_credential_store[2.5.1], news_merge[2.5.1],
            pipeline[1.4.0], qbzr[0.22.3], rewrite[0.6.4dev], svn[1.2.2],
            upload[1.2.0dev], xmloutput[0.8.8]
        encoding: 'cp1252', fsenc: 'mbcs', lang: 'en_US.UTF-8'

        *** Bazaar has encountered an internal error.  This probably indicates a
            bug in Bazaar.  You can help us fix it by filing a bug report at
                https://bugs.launchpad.net/bzr/+filebug
            including this traceback and a description of the problem.
`go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in C:\Users\t-chcoel\go\pkg\mod\cache\vcs\f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exit status 4:
        bzr: ERROR: httplib.IncompleteRead: IncompleteRead(34 bytes read)`

     `Traceback (most recent call last):
          File "bzrlib\commands.pyo", line 920, in exception_to_return_code
          File "bzrlib\commands.pyo", line 1131, in run_bzr
          File "bzrlib\commands.pyo", line 673, in run_argv_aliases
          File "bzrlib\commands.pyo", line 695, in run
          File "bzrlib\cleanup.pyo", line 136, in run_simple
          File "bzrlib\cleanup.pyo", line 166, in _do_with_cleanups
          File "bzrlib\builtins.pyo", line 1438, in run
          File "bzrlib\controldir.pyo", line 779, in open_tree_or_branch
          File "bzrlib\controldir.pyo", line 459, in _get_tree_branch
          File "bzrlib\bzrdir.pyo", line 1082, in open_branch
          File "bzrlib\branch.pyo", line 2375, in open
          File "bzrlib\controldir.pyo", line 687, in open
          File "bzrlib\controldir.pyo", line 716, in open_from_transport
          File "bzrlib\transport\__init__.pyo", line 1718, in do_catching_redirections
          File "bzrlib\controldir.pyo", line 704, in find_format
          File "bzrlib\controldir.pyo", line 1149, in find_format
          File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 235, in probe_transport
          File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 182, in probe_http_transport
          File "socket.pyo", line 348, in read
          File "httplib.pyo", line 522, in read
          File "httplib.pyo", line 565, in _read_chunked
        IncompleteRead: IncompleteRead(34 bytes read)`

        bzr 2.5.1 on python 2.6.6 (Windows-post2008Server-6.2.9200)
        arguments: ['bzr', 'branch', '--use-existing-dir',
            'https://launchpad.net/~niemeyer/gocheck/trunk', '.']
        plugins: bzrtools[2.5.0], changelog_merge[2.5.1], colo[0.4.0],
            explorer[1.2.2], fastimport[0.14.0dev], git[0.6.8], launchpad[2.5.1],
            loom[2.3.0dev], netrc_credential_store[2.5.1], news_merge[2.5.1],
            pipeline[1.4.0], qbzr[0.22.3], rewrite[0.6.4dev], svn[1.2.2],
            upload[1.2.0dev], xmloutput[0.8.8]
        encoding: 'cp1252', fsenc: 'mbcs', lang: 'en_US.UTF-8'

        *** Bazaar has encountered an internal error.  This probably indicates a
            bug in Bazaar.  You can help us fix it by filing a bug report at
                https://bugs.launchpad.net/bzr/+filebug
            including this traceback and a description of the problem.
go: error loading module requirements
make: *** [Makefile:86: agent] Error 1
`

**Comment by pjanotti** [comment]
I don't have a Windows machine at hand to investigate further but our AppVeyor CI was blocked by that... can you try to track who is pulling the dependency that requires bzr? `go mod why` should be your friend here. Also search an issue that I opened while investigating, I tried to open follow ups on other repos to try to get some traction...

**Comment by ChrisCoe** [comment]
I switched over to wsl and was able to avoid this problem. I can run the example/main.go file. When you say "build and validate it," would running that main.go file suffice? Also I am making these changes on my own private repo for now, do you mind if I add you as a reviewer?

**Comment by ChrisCoe** [comment]
@odeke-em When I heard that AppVeyor CI was blocked I figured I should not run this on windows. I forgot to mention you here sooner. Not sure what went wrong here.

**Comment by ChrisCoe** [comment]
Thank you for all the help here and on private chat. I was able to add my Azure Monitor Exporter to the oc agent in my local machine.
